"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleTagManager } from '@next/third-parties/google'
import { useEffect } from "react";
import { gtmPageView } from "@/lib/gtm";
import { usePathname } from 'next/navigation';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children}) {
  const pathName = usePathname();
  console.log("path",pathName);
  useEffect(()=>{
    const props = {
      page_title: pathName
    }
    gtmPageView(props)
  },[pathName])
  return (
    <html lang="en">
      <GoogleTagManager gtmId="GTM-MT5FW7GG" />
      <body>{children}</body>
    </html>
  );
}
